export const ROUTES = {
    LANDING: '/landing',
    INICIAR_SESION: '/iniciar-sesion',
    CREAR_CUENTA: '/crear-cuenta',
    CREAR_CUENTA_EXITO: '/crear-cuenta/exito',
    INICIO: '/dashboard/inicio',
    PERFIL: '/dashboard/perfil',
    TARJETAS: '/dashboard/tarjetas',
    TARJETAS__NUEVA: '/dashboard/tarjetas/nueva',
    ACTIVIDAD: '/dashboard/actividad',
    CARGAR_DINERO: '/dashboard/cargar-dinero',
    CARGAR_DINERO_TRANSFERENCIA: '/dashboard/cargar-dinero/transferencia',
    CARGAR_DINERO_TARJETA: '/dashboard/cargar-dinero/tarjeta',
    PAGAR_SERVICIOS: '/dashboard/pagar-servicios',
}
